// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvRYsHrGbax3FJUGdX5hH0MEKEDY6qVec',
    appId: '1:919173570715:web:d830076c94a28d117e663e',
    messagingSenderId: '919173570715',
    projectId: 'valet-club-dev-e2559',
    authDomain: 'valet-club-dev-e2559.firebaseapp.com',
    storageBucket: 'valet-club-dev-e2559.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmM3bXc4dV8j13rJS8ZjZfR-4YAeFlR3Y',
    appId: '1:919173570715:android:cfe917506208405d7e663e',
    messagingSenderId: '919173570715',
    projectId: 'valet-club-dev-e2559',
    storageBucket: 'valet-club-dev-e2559.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0K3zdE4oQYbu2s9_1W-bD29jfdhGEsRY',
    appId: '1:919173570715:ios:9fc66e79dfe6dc3d7e663e',
    messagingSenderId: '919173570715',
    projectId: 'valet-club-dev-e2559',
    storageBucket: 'valet-club-dev-e2559.appspot.com',
    iosBundleId: 'com.example.valetclubValet',
  );
}
